### ISSUE TITLE
Error: Unknown command 'Content-Management'

### ISSUE THREAD

**Issue by pringle-sz** [Sitecore/Sitecore.Demo.Platform#208] opened 2021-07-12 17:20 UTC
When running the command `docker-compose up -d` I get this error:

```
Step 35/46 : RUN .\build.ps1 -DeploymentTarget DockerBuild -Target Content-Management
 ---> Running in b4fb0dfc7ca1
Preparing to run build script...
Running build script...

Error: Unknown command 'Content-Management'.

       build.cake -target=Content-Management -deploymentTarget=DockerBuild
                          ^^^^^^^^^^^^^^^^^^ No such command

The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; .\build.ps1 -DeploymentTarget DockerBuild -Target Content-Management' returned a non-zero code: 1
ERROR: Service 'solution' failed to build : Build failed
```

I am using PowerShell 5.1.19041 rev 1023

**Comment by adoprog** [comment] 2021-07-13 11:56
Could you please try to run `docker-compose pull` first? Did you change anything in the .env file?

**Comment by pringle-sz** [comment] 2021-07-13 15:57
When I run `docker-compose pull`, I see this:

```
WARNING: The INTERNAL_NUGET_SOURCE variable is not set. Defaulting to a blank string.
WARNING: The SYSTEM_ACCESSTOKEN variable is not set. Defaulting to a blank string.
Pulling smtp                ... done
Pulling solr                ... done
Pulling solution            ... done
Pulling mssql               ... done
Pulling id                  ... done
Pulling ps                  ... done
Pulling xconnect            ... done
Pulling cm                  ... done
Pulling init                ... done
Pulling cd                  ... done
Pulling traefik             ... done
Pulling xdbsearchworker     ... done
Pulling xdbautomationworker ... done
WARNING: Some service image(s) must be built from source by running:
    docker-compose build solution
```

Running `docker-compose build solution` gives same build error.

I didn't make any manual changes to `.env` file:

```
COMPOSE_PROJECT_NAME=sitecore-xp0
SITECORE_DOCKER_REGISTRY=scr.sitecore.com/
SITECORE_VERSION=10.0.0
BASE_MODULE_VERSION=1000.0
SITECORE_ADMIN_PASSWORD=b
SQL_SA_PASSWORD=rY1IwTTSL0tNzT9DiHA
REPORTING_API_KEY=D0vw2Ris7EdJlrZtoLpt09gVZGIILV4oRckhxJVFKEBczjIULLBr2uU5ypXvfDdg5deW9JGHlUwfz4aC8okxibpSRHM5vBQ0Ixe2ZxlS9tbl82rx7xCpSMVMRYpIIME0
TELERIK_ENCRYPTION_KEY=RL]6Tku@]YG=Uyy/wVu4DCd~qBY$-I8aq+PpiUjjk<OQW#6u\8FjFm!TAVA<C^zo%^q-NNv@vs*|1`o$inT9q$uuZa]C=rtEG-:eBfjaIC=KlL/6J})ol^+3VNz:>yn*
SITECORE_ID_CERTIFICATE_PASSWORD=8izFg4WY
SITECORE_LICENSE=
CD_HOST=cd.lighthouse.localhost
CM_HOST=cm.lighthouse.localhost
ID_HOST=id.lighthouse.localhost
TRAEFIK_IMAGE=traefik:v2.2.0-windowsservercore-1809
TRAEFIK_ISOLATION=hyperv
ISOLATION=hyperv

REGISTRY=scr.sitecore.com/
DEMO_VERSION=1000.0
WINDOWSSERVERCORE_VERSION=ltsc2019
NANOSERVER_VERSION=1809
MARKETING_DEFINITIONS_APIKEY=DF7D20E837254C6FBFA2B854C295CB61
SITECORE_SERVICES_TOKEN_SECURITYKEY=HPz0d8yRXcvtFclPDjxTHZmcBywqUDxN
OPENCALAIS_ACCESSTOKEN=
CMP_CONTENTHUB=
CMP_SERVICEBUSENTITYPATHIN=
CMP_SERVICEBUSSUBSCRIPTION=
CMP_SERVICEBUSENTITYPATHOUT=
SFMC_CONNECTIONSTRING=client id=;client secret=;auth endpoint=https://example.com;rest endpoint=https://example.com;soap endpoint=https://example.com
DAM_URL=
CD_CONTAINERS_COUNT=1
SKIP_WARMUP_CD=false
HOST_LICENSE_FOLDER=E:\licenses\sitecore
RENDERING_HOST=www.lighthouse.localhost
SITECORE_IDSECRET=rutL78kyYUltvBOR01MjhSV87AV5abPcLLfAXZ7ucyEXsyyeGK0XLpnAOb6RsPq2
SITECORE_ID_CERTIFICATE=MIIKSQIBAzCCCgUGCSqGSIb3DQEHAaCCCfYEggnyMIIJ7jCCBg8GCSqGSIb3DQEHAaCCBgAEggX8MIIF+DCCBfQGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAiON24M9l9TaAICB9AEggTYH2CxjEJAfjh+kv8WBuvnemYabb9LRyc0MQvT3e390bxLLml/hRAEInFN+H2D2wSpnv1Auw73WNdQALCPzi6TBoePGlj8g5YbYVAIiB3aiNCbvlAA3Hv2DhAezm4VwVpyy5MlVqLiSz3hP17Nsj2E4l8di5TVKaDin+Al1J7ZSOFt1CnZqmPLkPUFx2LMn3XO/8QxRG62ZD9D8D8ApKdm9aD4+biDeUIUj1sDlML8Yw0lEnRJzFuN2wjVQvxZGzbRXilUVeH7YNJWCF4gkAPWaw0AfcHDtLSc3mBb3aFCEmW0sBsGWYFhwMsB5a6i6eqjtklz5qBBhZ5Qvsnw2SScJLIg4FiFB5nXjkNW1Xkr5tJO9/Y98/Yj0BltNqPHymNppNraFmdUlMRjYnQzY7PQA8Yp/qE9dk8jDgEdWGHsMvQLCIShkRvMysxT3DR9RcRoHNy2ZqAmoOoo9rSNQ+fxzKJmC7qFWYsG1OOxm13khVSfsqJaG+oSy+A+jnRrSBr0ZKCElNIux0KPSLNNkOHj/KxUrh4OfjISIB7j+1aonjcAR6jINpTwLEXHOFKYd+Ry1BTHI+uYyYLMPdtM9O+xve4h/emFBui1RQSHauDj2VfdLiOsV9mSevVeJQRbepPvG3eXqrxoGYZfCQLIvlrcPGx5QrErGeI9hjm3FZNs4Pr0gdPDhBv7djGn02COrEYmpq90sj44SFjvHRaeot+uWHfGbxQKRYAmU5xm7IOiZ2DMG/9UcpSt8u/RaY8gs681EfmJd2n1LrG69Ko5kQHBxdx5R5GAu6gih0WPLZuDeg7rit7bd3XasZOde+bDJC51jf2mU9e32TgQ9AFohX5UUn7e2EsjIk/fZm+Z+tfubfxhWXQXOgm+SU/r6gmu0GwXSOMghS9gOlMJvdSSab1f1R564bZfLt4zlYVdpLJ4MAbYYC/pkx8eftbuBpy86O6agBUfM+3cB+FS3X2k0usOQHRAVe8e8G+53KHekEoElO0ROGuUgGDHc7EVX2OZAKFvh4m8D7lxPNwIoEkVFDkdktX3vXHT5ZQ4dIjqJcgC9GVyQ7HiY7xuAhOZluugqmLZnPEQLBCvouFEPnnSJUWc0EdAeaG1UWs29zT0XEl1tELVRrgtsOsmmOFT7/sksAJjxNIW31AsYNMKBm1n/Q7NXg2UeFhHfLk3AAvDQhCXoRpL03ZTAy4mGT7r9nXUyjaboJRwxTgH5mQrI5QNZq7WeXGGRAc/wUMzehBTnbRCXqjbEaHtxKJA+BJjjAp+7w1NfH+pILHmyB9/bxM+2WMNQtCF3EcHGu4NwF+EeqlKAg9Sl6sB5OXggf+n/gNMUdCXClVBEd8kOvnFAhZRCF977yL3UZ3LphLnp/IUWorCjvWPhdfn7LbmmpGjvikqbG+GBryrrEH/rC0zca1eR/8KtD4td3u/FWg7GNwhD2/wtdjiHwb9bkv/kgyrBdsRyGP24hZhD6axn11Oz5SOGGcUifEbRhmDv8dgZusrFYUr4L11cbmtoQVbL/VuFnodknjY4xUIIQVTrU6+FFhaBRIfygdunuXeb78jfH+V9fs4fUex2Y9j7+PybijfLlxOo7L++lGULKvpmxXiWD1RLmY35E3DyQgbmn5W3Aat0Yn9ANErADDtUdAVojGB4jANBgkrBgEEAYI3EQIxADATBgkqhkiG9w0BCRUxBgQEAQAAADBdBgkqhkiG9w0BCRQxUB5OAHQAZQAtADEAYgBlAGMAMQA0AGEAZAAtADIAOAAwADIALQA0ADkANwA1AC0AYgBiADYANwAtAGQANQBiADUAMgAxADQAZgAxADYANwA5MF0GCSsGAQQBgjcRATFQHk4ATQBpAGMAcgBvAHMAbwBmAHQAIABTAG8AZgB0AHcAYQByAGUAIABLAGUAeQAgAFMAdABvAHIAYQBnAGUAIABQAHIAbwB2AGkAZABlAHIwggPXBgkqhkiG9w0BBwagggPIMIIDxAIBADCCA70GCSqGSIb3DQEHATAcBgoqhkiG9w0BDAEDMA4ECGuu1AQtztBJAgIH0ICCA5A1DPEhG5VHZuNtfOa8s+3wwzzMsr10PxJ9ICPTRXO9LffkqNvh2afHzWKRQeS12eR6P7uGwcYbyraE52RKX30imHjSsimueiRzG9pWA96QAvdO7xkoiOOxMWiUIb2pIdHdrsRTJkKjBTbJzVsWbOpzm0VW6wpNPGt/Ccb+qk14rXaG/euKiaknzOeh973gVMIK0ug8NL+ujoRW/elFRw+JP4Zv8bUDAnfE05Su0y1YlgCHEy0G1f7mcTl+dwi+IdWZ1UP/DyO+GWVuNWU6cVyJyHJ6kLMI3SdHFE5f7DBWziP8H1mw6Jz5ZgHhU5jid1NSuKMHG1s6xymiP22NhjC4OA5V3jghkuU0LIFMqTM80I+HG3JJI1XbqFgEBAzSFOIWHTRiLfR4lG5UlvaW5anme+NTdrAsyp6Zcw9iFnQCSLERhOSNjrstbkisjJ106opk17lJaeL1dPn2msZzsO77hyoj7ocO6gcV3K6dkxKcwMlah6JSy4ig9IhAO6Id2fEx1Aoax4ir7Gyy+p6gau2+rciYOP1RnyZ6ejpr8g67mHUSYYhjMAQwVUgnnJW32gzVVGQlHHBcm93QrMt3uqT3OyLPbxms+SHkvXaGWCbFCsyFRkDLPltqzq1uSPkC2Wm2IsR2ajy/2LRDVkWFOcb73qndgEs9SJvqyb999JvS3X4UyR42DdShjMtXYhAvbygwDFWo4ACKEzUjJ89a+FdWJ4+lbhATzBVsKHtvv0IPONdJMTsPNX270j98C8OR8Ky5j8/6JzpExvSKRqyKevJjDoux266sonGH7YNCgN6twRfHTUh0UNoDbL6bP3HtqfZH+gNe3pSwqpr070i8xphX5RyGYqTJaO2NpOSEvPRcQab1btizCeUlTrOGaAYfr/GBn+2vqCd4jR6GPJ7JhI1NNy9Ob+C/vM85dtgm4D+AX8KbDbuM5jsRRG5rCYJGVFrkfByTEsRzsrbUSFzhkW+npZKKyNBqKrpn92k5vF72XFAPd3519uo94Z2XXaAH4wvI3Ox7mINkkXMMSm0pNsHtrMNbDGqbGEoU7ppUs7uZVQlt7PqvrVFc1LjIvgW79G6bySZeUHhVRBA0S7y7TKTSOkGBtIzu3qNqEBH320NRycOcfn6jMuh41jz/U4xCbDy8Ui97J+P5pw9Wp/vGWSAPAHjDwoQHh0MpxUIaNZOrabY2aSOxIm4xLK0PSDt85cIwOzAfMAcGBSsOAwIaBBTmgLo6+IgjO4cghG4JGxuwhgqAKQQU0EIjNearV3x37OGE3eva5GHsG2oCAgfQ
```

**Comment by munagavenkat** [comment] 2021-07-14 13:30
I got similar issue. Reproduce steps for error. 
1. Get Sitecore.Demo.Platform 1000.0.5
2. .\init.ps1 -InitEnv -LicenseXmlPath C:\license\license.xml -AdminPassword b
3. docker-compose pull
4. docker-compose up -d

`Error: Unknown command 'Content-Management'.

       build.cake -target=Content-Management -deploymentTarget=DockerBuild
                          ^^^^^^^^^^^^^^^^^^ No such command`

I resolved the error by changing build.cake arguments by adding two dashes as shown below in the build.ps1 powershell file.

![image](https://user-images.githubusercontent.com/30612904/125629806-2d4b6f5d-f6b9-4d4a-8c33-38d0afcf98fb.png)

please let me know if any other way to resolve the error.

**Comment by pringle-sz** [comment] 2021-07-14 15:49
I get past this error with @munagavenkat workaround. Next is this error.

```
----------------------------------------
Setup
----------------------------------------
Sitecore Demo Build Tasks

========================================
Publish-FrontEnd-Project
========================================
An error occurred when executing task 'Publish-FrontEnd-Project'.
Error: One or more errors occurred.
        Method not found: 'Cake.Core.IO.FilePathCollection Cake.Common.IO.GlobbingAliases.GetFiles(Cake.Core.ICakeContext, System.String)'.
The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; .\build.ps1 -DeploymentTarget DockerBuild -Target Content-Management' returned a non-zero code: 1
ERROR: Service 'solution' failed to build : Build failed
```

**Comment by munagavenkat** [comment] 2021-07-15 14:52
The root cause of the below issue is Cake version. 

`An error occurred when executing task 'Publish-FrontEnd-Project'.
Error: One or more errors occurred.
        Method not found: 'Cake.Core.IO.FilePathCollection Cake.Common.IO.GlobbingAliases.GetFiles(Cake.Core.ICakeContext, System.String)'.`

Sitecore.Demo.Platform 1000.0.5 repo is using Cake version "**0.38.1**". You can check as show  in below diagram. But when we run docker-compose up -d command, while building solution container service, it is downloading Cake version as "1.1.0" and throwing exception.
![image](https://user-images.githubusercontent.com/30612904/125806003-c32d072b-cf41-4bf7-8ef6-9ea21cc519e4.png)

**Solution**
Modify build.ps1 to point to Cake "0.38.1" . For that, I uploaded packages.config  (which has "0.38.1" version) file to my blob storage and gave reference (highlighted in red) instead of existing Url. I also added few commands (highlighted in white) to monitor cake version. 

https://cakebuild.net/download/bootstrapper/packages  -  "1.1.0"
https://demostpackage.blob.core.windows.net/cakepackages/packages.config - "0.38.1" - you can use this url temporarily to verify but I will be going to delete after few days.

![image](https://user-images.githubusercontent.com/30612904/125808411-e5004af2-31fb-47f0-ac7e-854f48193c1c.png)

Anyone can share public specific cake version packages.config if you know.

**Comment by jflheureux** [comment] 2021-09-09 18:55
Very good investigative work done here @munagavenkat. This issue has been fixed in commit https://github.com/Sitecore/Sitecore.Demo.Platform/commit/122685ef7a1c0a6f5d295578c4c113d57d1874e7 in February 2021 and is included in "main" branch.

**Closed by jflheureux** 2021-09-09 18:55 UTC
