### ISSUE TITLE
Containers failing to start with UnauthorizedAccessException

### ISSUE THREAD

**Issue by jhansen81** [Sitecore/Sitecore.Demo.Platform#216] opened 2022-05-12 15:30 UTC
When running `docker-compose up -d` I'm getting containers that fail to start.  When I look at the logs I'm seeing variations on this just with different paths depending upon the containers:

`Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\sps' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.EnumerateFileSystemInfos(String searchPattern, SearchOption searchOption)
   at Microsoft.Extensions.FileSystemGlobbing.Abstractions.DirectoryInfoWrapper.EnumerateFileSystemInfos()+MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at Microsoft.Extensions.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Extensions.FileSystemGlobbing.Internal.MatcherContext.Execute()
   at Microsoft.Extensions.FileSystemGlobbing.Matcher.Execute(DirectoryInfoBase directoryInfo)
   at Microsoft.Extensions.FileSystemGlobbing.MatcherExtensions.GetResultsInFullPath(Matcher matcher, String directoryPath)
   at Sitecore.Framework.Runtime.Plugins.DefaultPluginManager.ResolvePlugins(String matchPath, String contentRootPath, IAssemblyResolver assemblyResolver)
   at Sitecore.Framework.Runtime.Plugins.DefaultPluginManager.ResolveBuildTimePlugins(IAssemblyResolver defaultAssemblyResolver, String contentRootPath)
   at Sitecore.Framework.Runtime.Plugins.DefaultPluginManager.ResolvePlugins(IAssemblyResolver defaultAssemblyResolver, IAssemblyResolver runtimeAssemblyResolver, ISitecorePluginFilterStrategy filterStrategy, ISitecorePluginSortStrategy sortStrategy, ISitecoreHostingEnvironment host)
   at Sitecore.Framework.Runtime.Plugins.DefaultPluginManager..ctor(ISitecoreHostingEnvironment host, IAssemblyResolverFactory assemblyResolverFactory, ISitecorePluginFilterStrategy filterStrategy, ISitecorePluginSortStrategy sortStrategy, IOptions`1 options)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Sitecore.Framework.Runtime.Licensing.ConsumptionTracking.Initialize(License license, ServiceProvider services)
   at Sitecore.Framework.Runtime.Commands.SitecoreHostCommand.OnExecuteAsync(CommandLineApplication app)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at Sitecore.Program.<Main>(String[] args)`

I have followed all set up instructions including setting Docker to use Windows containers and enabling experimental features.

**Comment by jflheureux** [comment] 2022-05-12 15:35
This is caused by an update made to the Docker Desktop product. Versions 4.7.1 and 4.8.1 are known to have an issue with ACLs when starting Windows containers. It will be fixed in version 4.9.0 (currently in pre-release) and newer versions. The work around is to downgrade Docker Desktop to version 4.6.1.

Here is the Docker issue: https://github.com/docker/for-win/issues/12701

**Closed** 2022-05-12 15:36 UTC

**Comment by jhansen81** [comment] 2022-05-12 16:23
Thanks, Jeff.  Can the documentation be updated to reflect that?  Might save others from running into the same problem.
